/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#31302d",
        "background": "#fcf9f4",
        "on-tertiary-fixed-variant": "#5b4300",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#1e5122",
        "inverse-on-surface": "#f3f0eb",
        "on-error": "#ffffff",
        "secondary-container": "#b7f1b1",
        "inverse-primary": "#ffb4a4",
        "surface-tint": "#aa361e",
        "secondary-fixed": "#b7f1b1",
        "on-primary-fixed-variant": "#891e07",
        "surface-container-high": "#ebe8e3",
        "on-surface-variant": "#58413c",
        "tertiary-fixed-dim": "#eec058",
        "surface-bright": "#fcf9f4",
        "tertiary-fixed": "#ffdf9f",
        "on-tertiary-fixed": "#261a00",
        "on-primary-fixed": "#3e0500",
        "surface-container-low": "#f6f3ee",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#002205",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#fffaff",
        "outline": "#8c716b",
        "error": "#ba1a1a",
        "primary": "#a6331b",
        "surface-container": "#f0ede9",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#9cd597",
        "secondary": "#366937",
        "on-secondary-container": "#3c703d",
        "surface-variant": "#e5e2dd",
        "on-surface": "#1c1c19",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e5e2dd",
        "primary-container": "#c84b31",
        "tertiary-container": "#946e04",
        "surface": "#fcf9f4",
        "surface-dim": "#dcdad5",
        "tertiary": "#755700",
        "primary-fixed": "#ffdad3",
        "on-background": "#1c1c19",
        "primary-fixed-dim": "#ffb4a4",
        "on-primary-container": "#fffbff",
        "outline-variant": "#e0bfb9",
        "surface-container-lowest": "#ffffff"
      },
      fontFamily: {
        "headline": ["Cormorant Garamond", "serif"],
        "body": ["Jost", "sans-serif"],
        "label": ["Jost", "sans-serif"],
        "technical": ["Courier Prime", "monospace"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
